version: '3'

services:
  db:
    build: ./db/
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      # Define the credentials to use for the database initialized at first container run.
      # These should NOT be hard-coded in a production environment and are only defined here for a simple setup.
      - POSTGRES_DB=tester_matcher
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=notsecret
  api:
    build: ./api/
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      # These should NOT be hard-coded in a production environment and are only defined here for a simple setup.
      - APP_DEBUG=True
      - APP_KEY=xxsyxo%di^nc1m(-9bo*-rpw!6g7-^98w**jy_@02b6qmf@9%x
      - DB_NAME=tester_matcher
      - DB_USER=app
      - DB_PASSWORD=notsecret
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  ui:
    build: ./ui/
    volumes:
      - ./ui/:/src/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - api